// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: genaiprovider/custom_cost.proto

package genaiprovider

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CustomCostSource_GetCustomCosts_FullMethodName = "/genaiprovider.CustomCostSource/GetCustomCosts"
)

// CustomCostSourceClient is the client API for CustomCostSource service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomCostSourceClient interface {
	GetCustomCosts(ctx context.Context, in *GetCustomCostsRequest, opts ...grpc.CallOption) (*GetCustomCostsResponse, error)
}

type customCostSourceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomCostSourceClient(cc grpc.ClientConnInterface) CustomCostSourceClient {
	return &customCostSourceClient{cc}
}

func (c *customCostSourceClient) GetCustomCosts(ctx context.Context, in *GetCustomCostsRequest, opts ...grpc.CallOption) (*GetCustomCostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCustomCostsResponse)
	err := c.cc.Invoke(ctx, CustomCostSource_GetCustomCosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomCostSourceServer is the server API for CustomCostSource service.
// All implementations must embed UnimplementedCustomCostSourceServer
// for forward compatibility.
type CustomCostSourceServer interface {
	GetCustomCosts(context.Context, *GetCustomCostsRequest) (*GetCustomCostsResponse, error)
	mustEmbedUnimplementedCustomCostSourceServer()
}

// UnimplementedCustomCostSourceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCustomCostSourceServer struct{}

func (UnimplementedCustomCostSourceServer) GetCustomCosts(context.Context, *GetCustomCostsRequest) (*GetCustomCostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCustomCosts not implemented")
}
func (UnimplementedCustomCostSourceServer) mustEmbedUnimplementedCustomCostSourceServer() {}
func (UnimplementedCustomCostSourceServer) testEmbeddedByValue()                          {}

// UnsafeCustomCostSourceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomCostSourceServer will
// result in compilation errors.
type UnsafeCustomCostSourceServer interface {
	mustEmbedUnimplementedCustomCostSourceServer()
}

func RegisterCustomCostSourceServer(s grpc.ServiceRegistrar, srv CustomCostSourceServer) {
	// If the following call panics, it indicates UnimplementedCustomCostSourceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CustomCostSource_ServiceDesc, srv)
}

func _CustomCostSource_GetCustomCosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomCostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomCostSourceServer).GetCustomCosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CustomCostSource_GetCustomCosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomCostSourceServer).GetCustomCosts(ctx, req.(*GetCustomCostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomCostSource_ServiceDesc is the grpc.ServiceDesc for CustomCostSource service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomCostSource_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genaiprovider.CustomCostSource",
	HandlerType: (*CustomCostSourceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCustomCosts",
			Handler:    _CustomCostSource_GetCustomCosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genaiprovider/custom_cost.proto",
}
