// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: genaiprovider/custom_cost.proto

package genaiprovider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mirror of your EfficiencyMetrics struct
type EfficiencyMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CostPer_1MInput  float64                `protobuf:"fixed64,1,opt,name=cost_per_1m_input,json=costPer1mInput,proto3" json:"cost_per_1m_input,omitempty"`
	CostPer_1MOutput float64                `protobuf:"fixed64,2,opt,name=cost_per_1m_output,json=costPer1mOutput,proto3" json:"cost_per_1m_output,omitempty"`
	CostPer_1MTotal  float64                `protobuf:"fixed64,3,opt,name=cost_per_1m_total,json=costPer1mTotal,proto3" json:"cost_per_1m_total,omitempty"`
	TokensPerGpuSec  float64                `protobuf:"fixed64,4,opt,name=tokens_per_gpu_sec,json=tokensPerGpuSec,proto3" json:"tokens_per_gpu_sec,omitempty"`
	CacheSavings     float64                `protobuf:"fixed64,5,opt,name=cache_savings,json=cacheSavings,proto3" json:"cache_savings,omitempty"`
	GpuUtilPercent   float64                `protobuf:"fixed64,6,opt,name=gpu_util_percent,json=gpuUtilPercent,proto3" json:"gpu_util_percent,omitempty"`
	GpuWaste         float64                `protobuf:"fixed64,7,opt,name=gpu_waste,json=gpuWaste,proto3" json:"gpu_waste,omitempty"`
	EfficiencyStatus string                 `protobuf:"bytes,8,opt,name=efficiency_status,json=efficiencyStatus,proto3" json:"efficiency_status,omitempty"`
	MigUtilization   float64                `protobuf:"fixed64,9,opt,name=mig_utilization,json=migUtilization,proto3" json:"mig_utilization,omitempty"`
	UnallocatedCost  float64                `protobuf:"fixed64,10,opt,name=unallocated_cost,json=unallocatedCost,proto3" json:"unallocated_cost,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EfficiencyMetrics) Reset() {
	*x = EfficiencyMetrics{}
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EfficiencyMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EfficiencyMetrics) ProtoMessage() {}

func (x *EfficiencyMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EfficiencyMetrics.ProtoReflect.Descriptor instead.
func (*EfficiencyMetrics) Descriptor() ([]byte, []int) {
	return file_genaiprovider_custom_cost_proto_rawDescGZIP(), []int{0}
}

func (x *EfficiencyMetrics) GetCostPer_1MInput() float64 {
	if x != nil {
		return x.CostPer_1MInput
	}
	return 0
}

func (x *EfficiencyMetrics) GetCostPer_1MOutput() float64 {
	if x != nil {
		return x.CostPer_1MOutput
	}
	return 0
}

func (x *EfficiencyMetrics) GetCostPer_1MTotal() float64 {
	if x != nil {
		return x.CostPer_1MTotal
	}
	return 0
}

func (x *EfficiencyMetrics) GetTokensPerGpuSec() float64 {
	if x != nil {
		return x.TokensPerGpuSec
	}
	return 0
}

func (x *EfficiencyMetrics) GetCacheSavings() float64 {
	if x != nil {
		return x.CacheSavings
	}
	return 0
}

func (x *EfficiencyMetrics) GetGpuUtilPercent() float64 {
	if x != nil {
		return x.GpuUtilPercent
	}
	return 0
}

func (x *EfficiencyMetrics) GetGpuWaste() float64 {
	if x != nil {
		return x.GpuWaste
	}
	return 0
}

func (x *EfficiencyMetrics) GetEfficiencyStatus() string {
	if x != nil {
		return x.EfficiencyStatus
	}
	return ""
}

func (x *EfficiencyMetrics) GetMigUtilization() float64 {
	if x != nil {
		return x.MigUtilization
	}
	return 0
}

func (x *EfficiencyMetrics) GetUnallocatedCost() float64 {
	if x != nil {
		return x.UnallocatedCost
	}
	return 0
}

// Mirror of your GenAIAttributes struct
type GenAIAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowPhase string                 `protobuf:"bytes,1,opt,name=workflow_phase,json=workflowPhase,proto3" json:"workflow_phase,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ModelVersion  string                 `protobuf:"bytes,3,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Accelerator   string                 `protobuf:"bytes,5,opt,name=accelerator,proto3" json:"accelerator,omitempty"`
	GpuUuid       string                 `protobuf:"bytes,6,opt,name=gpu_uuid,json=gpuUuid,proto3" json:"gpu_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenAIAttributes) Reset() {
	*x = GenAIAttributes{}
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAIAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAIAttributes) ProtoMessage() {}

func (x *GenAIAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenAIAttributes.ProtoReflect.Descriptor instead.
func (*GenAIAttributes) Descriptor() ([]byte, []int) {
	return file_genaiprovider_custom_cost_proto_rawDescGZIP(), []int{1}
}

func (x *GenAIAttributes) GetWorkflowPhase() string {
	if x != nil {
		return x.WorkflowPhase
	}
	return ""
}

func (x *GenAIAttributes) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GenAIAttributes) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *GenAIAttributes) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenAIAttributes) GetAccelerator() string {
	if x != nil {
		return x.Accelerator
	}
	return ""
}

func (x *GenAIAttributes) GetGpuUuid() string {
	if x != nil {
		return x.GpuUuid
	}
	return ""
}

// The main response object
type GenAIWorkload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	ModelName     string                 `protobuf:"bytes,2,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	TotalTokens   int64                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	TotalCost     float64                `protobuf:"fixed64,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkflowPhase string                 `protobuf:"bytes,6,opt,name=workflow_phase,json=workflowPhase,proto3" json:"workflow_phase,omitempty"`
	MigProfile    string                 `protobuf:"bytes,7,opt,name=mig_profile,json=migProfile,proto3" json:"mig_profile,omitempty"`
	GpuEfficiency float64                `protobuf:"fixed64,8,opt,name=gpu_efficiency,json=gpuEfficiency,proto3" json:"gpu_efficiency,omitempty"`
	// Nesting your detailed sub-structs
	Efficiency    *EfficiencyMetrics `protobuf:"bytes,9,opt,name=efficiency,proto3" json:"efficiency,omitempty"`
	Attributes    *GenAIAttributes   `protobuf:"bytes,10,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenAIWorkload) Reset() {
	*x = GenAIWorkload{}
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenAIWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenAIWorkload) ProtoMessage() {}

func (x *GenAIWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenAIWorkload.ProtoReflect.Descriptor instead.
func (*GenAIWorkload) Descriptor() ([]byte, []int) {
	return file_genaiprovider_custom_cost_proto_rawDescGZIP(), []int{2}
}

func (x *GenAIWorkload) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *GenAIWorkload) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *GenAIWorkload) GetTotalTokens() int64 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *GenAIWorkload) GetTotalCost() float64 {
	if x != nil {
		return x.TotalCost
	}
	return 0
}

func (x *GenAIWorkload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenAIWorkload) GetWorkflowPhase() string {
	if x != nil {
		return x.WorkflowPhase
	}
	return ""
}

func (x *GenAIWorkload) GetMigProfile() string {
	if x != nil {
		return x.MigProfile
	}
	return ""
}

func (x *GenAIWorkload) GetGpuEfficiency() float64 {
	if x != nil {
		return x.GpuEfficiency
	}
	return 0
}

func (x *GenAIWorkload) GetEfficiency() *EfficiencyMetrics {
	if x != nil {
		return x.Efficiency
	}
	return nil
}

func (x *GenAIWorkload) GetAttributes() *GenAIAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type GetCustomCostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomCostsRequest) Reset() {
	*x = GetCustomCostsRequest{}
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomCostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomCostsRequest) ProtoMessage() {}

func (x *GetCustomCostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomCostsRequest.ProtoReflect.Descriptor instead.
func (*GetCustomCostsRequest) Descriptor() ([]byte, []int) {
	return file_genaiprovider_custom_cost_proto_rawDescGZIP(), []int{3}
}

func (x *GetCustomCostsRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetCustomCostsRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type GetCustomCostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*GenAIWorkload       `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomCostsResponse) Reset() {
	*x = GetCustomCostsResponse{}
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomCostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomCostsResponse) ProtoMessage() {}

func (x *GetCustomCostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_genaiprovider_custom_cost_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomCostsResponse.ProtoReflect.Descriptor instead.
func (*GetCustomCostsResponse) Descriptor() ([]byte, []int) {
	return file_genaiprovider_custom_cost_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomCostsResponse) GetWorkloads() []*GenAIWorkload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

var File_genaiprovider_custom_cost_proto protoreflect.FileDescriptor

const file_genaiprovider_custom_cost_proto_rawDesc = "" +
	"\n" +
	"\x1fgenaiprovider/custom_cost.proto\x12\rgenaiprovider\"\xb0\x03\n" +
	"\x11EfficiencyMetrics\x12)\n" +
	"\x11cost_per_1m_input\x18\x01 \x01(\x01R\x0ecostPer1mInput\x12+\n" +
	"\x12cost_per_1m_output\x18\x02 \x01(\x01R\x0fcostPer1mOutput\x12)\n" +
	"\x11cost_per_1m_total\x18\x03 \x01(\x01R\x0ecostPer1mTotal\x12+\n" +
	"\x12tokens_per_gpu_sec\x18\x04 \x01(\x01R\x0ftokensPerGpuSec\x12#\n" +
	"\rcache_savings\x18\x05 \x01(\x01R\fcacheSavings\x12(\n" +
	"\x10gpu_util_percent\x18\x06 \x01(\x01R\x0egpuUtilPercent\x12\x1b\n" +
	"\tgpu_waste\x18\a \x01(\x01R\bgpuWaste\x12+\n" +
	"\x11efficiency_status\x18\b \x01(\tR\x10efficiencyStatus\x12'\n" +
	"\x0fmig_utilization\x18\t \x01(\x01R\x0emigUtilization\x12)\n" +
	"\x10unallocated_cost\x18\n" +
	" \x01(\x01R\x0funallocatedCost\"\xd6\x01\n" +
	"\x0fGenAIAttributes\x12%\n" +
	"\x0eworkflow_phase\x18\x01 \x01(\tR\rworkflowPhase\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12#\n" +
	"\rmodel_version\x18\x03 \x01(\tR\fmodelVersion\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12 \n" +
	"\vaccelerator\x18\x05 \x01(\tR\vaccelerator\x12\x19\n" +
	"\bgpu_uuid\x18\x06 \x01(\tR\agpuUuid\"\x99\x03\n" +
	"\rGenAIWorkload\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x1d\n" +
	"\n" +
	"model_name\x18\x02 \x01(\tR\tmodelName\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x03R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"total_cost\x18\x04 \x01(\x01R\ttotalCost\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12%\n" +
	"\x0eworkflow_phase\x18\x06 \x01(\tR\rworkflowPhase\x12\x1f\n" +
	"\vmig_profile\x18\a \x01(\tR\n" +
	"migProfile\x12%\n" +
	"\x0egpu_efficiency\x18\b \x01(\x01R\rgpuEfficiency\x12@\n" +
	"\n" +
	"efficiency\x18\t \x01(\v2 .genaiprovider.EfficiencyMetricsR\n" +
	"efficiency\x12>\n" +
	"\n" +
	"attributes\x18\n" +
	" \x01(\v2\x1e.genaiprovider.GenAIAttributesR\n" +
	"attributes\"?\n" +
	"\x15GetCustomCostsRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"T\n" +
	"\x16GetCustomCostsResponse\x12:\n" +
	"\tworkloads\x18\x01 \x03(\v2\x1c.genaiprovider.GenAIWorkloadR\tworkloads2q\n" +
	"\x10CustomCostSource\x12]\n" +
	"\x0eGetCustomCosts\x12$.genaiprovider.GetCustomCostsRequest\x1a%.genaiprovider.GetCustomCostsResponseBIZGgithub.com/nXtCyberNet/opencost-plugins/pkg/plugins/genai/genaiproviderb\x06proto3"

var (
	file_genaiprovider_custom_cost_proto_rawDescOnce sync.Once
	file_genaiprovider_custom_cost_proto_rawDescData []byte
)

func file_genaiprovider_custom_cost_proto_rawDescGZIP() []byte {
	file_genaiprovider_custom_cost_proto_rawDescOnce.Do(func() {
		file_genaiprovider_custom_cost_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_genaiprovider_custom_cost_proto_rawDesc), len(file_genaiprovider_custom_cost_proto_rawDesc)))
	})
	return file_genaiprovider_custom_cost_proto_rawDescData
}

var file_genaiprovider_custom_cost_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_genaiprovider_custom_cost_proto_goTypes = []any{
	(*EfficiencyMetrics)(nil),      // 0: genaiprovider.EfficiencyMetrics
	(*GenAIAttributes)(nil),        // 1: genaiprovider.GenAIAttributes
	(*GenAIWorkload)(nil),          // 2: genaiprovider.GenAIWorkload
	(*GetCustomCostsRequest)(nil),  // 3: genaiprovider.GetCustomCostsRequest
	(*GetCustomCostsResponse)(nil), // 4: genaiprovider.GetCustomCostsResponse
}
var file_genaiprovider_custom_cost_proto_depIdxs = []int32{
	0, // 0: genaiprovider.GenAIWorkload.efficiency:type_name -> genaiprovider.EfficiencyMetrics
	1, // 1: genaiprovider.GenAIWorkload.attributes:type_name -> genaiprovider.GenAIAttributes
	2, // 2: genaiprovider.GetCustomCostsResponse.workloads:type_name -> genaiprovider.GenAIWorkload
	3, // 3: genaiprovider.CustomCostSource.GetCustomCosts:input_type -> genaiprovider.GetCustomCostsRequest
	4, // 4: genaiprovider.CustomCostSource.GetCustomCosts:output_type -> genaiprovider.GetCustomCostsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_genaiprovider_custom_cost_proto_init() }
func file_genaiprovider_custom_cost_proto_init() {
	if File_genaiprovider_custom_cost_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_genaiprovider_custom_cost_proto_rawDesc), len(file_genaiprovider_custom_cost_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_genaiprovider_custom_cost_proto_goTypes,
		DependencyIndexes: file_genaiprovider_custom_cost_proto_depIdxs,
		MessageInfos:      file_genaiprovider_custom_cost_proto_msgTypes,
	}.Build()
	File_genaiprovider_custom_cost_proto = out.File
	file_genaiprovider_custom_cost_proto_goTypes = nil
	file_genaiprovider_custom_cost_proto_depIdxs = nil
}
